//Module pour stocker les infos priv�s dans un fichier .env
require('dotenv').config()

//Module export
module.exports = {
    "monster": {
        "Trinité": "Trinity",
        "Poupée de chiffon": "Ragdoll",
        "Camille": "Camilla",
        "Joséphine": "Josephine",
        "Refroidissement": "Chilling",
        "Herné": "Herne",
        "Galion": "Galleon",
        "Gallion": "Galleon",
        "Borsalino": "Fedora",
        "Tracteur": "Tractor",
        "Ophelia": "Ophilia",
        "Ophélia": "Ophilia",
        "Fumée": "Smokey",
        "Chloé": "Chloe",
        "Fer": "Iron",
        "Léo": "Leo",
        "Mélia": "Mellia",
        "Mélissa": "Melissa",
        "Venteux": "Windy",
        "Cuivre": "Copper",
        "Grue": "Crane",
        "Férélia": "Felleria",
        "Brumeux": "Misty",
        "Marbre": "Marble",
        "Argent": "Silver",
        "Poussiéreux": "Dusky",
        "Hyanès": "Hyanes",
        "Frégate": "Frigate",
        "Robot": "Crawler",
        "Granit": "Granite",
        "Cassandre": "Cassandra",
        "Bélial": "Belial",
        "Sharon": "Sharron",
        "Méphisto": "Mephisto",
        "Carabine": "Carbine",
        "Brick": "Brig",
        "Foreur": "Driller",
        "Belzébuth": "Beelzebub",
        "Léona": "Leona",
        "Rachid": "Rasheed",
        "Kumaé": "Kumae",
        "Buldo": "Bulldozer",
        "Bulldo": "Bulldozer",
        "Tesa": "Tesarion",
        "Ken": "KEN",
        "Mhw": "Mei Hou Wang",
        "Fy": "Feng Yan",
        "Xz": "Xing Zhe",
        "Homunculus Water": 'Homunculus - Attack (Water)',
        "Homunculus Fire": 'Homunculus - Attack (Fire)',
        "Homunculus Wind": 'Homunculus - Attack (Wind)',
        "Homunculus Light": 'Homunculus - Support (Light)',
        "Homunculus Dark": 'Homunculus - Support (Dark)',
        "Homunculus Eau": 'Homunculus - Attack (Water)',
        "Homunculus Feu": 'Homunculus - Attack (Fire)',
        "Homunculus Vent": 'Homunculus - Attack (Wind)',
        "Homunculus Lumière": 'Homunculus - Support (Light)',
        "Homunculus Lumiere": 'Homunculus - Support (Light)',
        "Homunculus Sombre": 'Homunculus - Support (Dark)',
        "Homunculus Sonbre": 'Homunculus - Support (Dark)'
    }
}