//Module pour stocker les infos privés dans un fichier .env
require('dotenv').config()

//Module export
module.exports = {
    "monster": {
        "Trinité": "Trinity",
        "Poupée de chiffon": "Ragdoll",
        "Camille": "Camilla",
        "Joséphine": "Josephine",
        "Refroidissement": "Chilling",
        "Herné": "Herne",
        "Galion": "Galleon",
        "Borsalino": "Fedora",
        "Tracteur": "Tractor",
        "Ophelia": "Ophilia",
        "Ophélia": "Ophilia",
        "Fumée": "Smokey",
        "Chloé": "Chloe",
        "Fer": "Iron",
        "Léo": "Leo",
        "Mélia": "Mellia",
        "Mélissa": "Melissa",
        "Venteux": "Windy",
        "Cuivre": "Copper",
        "Grue": "Crane",
        "Férélia": "Felleria",
        "Brumeux": "Misty",
        "Marbre": "Marble",
        "Argent": "Silver",
        "Poussiéreux": "Dusky",
        "Hyanès": "Hyanes",
        "Frégate": "Frigate",
        "Robot": "Crawler",
        "Granit": "Granite",
        "Cassandre": "Cassandra",
        "Bélial": "Belial",
        "Sharon": "Sharron",
        "Méphisto": "Mephisto",
        "Carabine": "Carbine",
        "Brick": "Brig",
        "Foreur": "Driller",
        "Belzébuth": "Beelzebub",
        "Léona": "Leona",
        "Rachid": "Rasheed",
        "Kumaé": "Kumae",
        "Buldo": "Bulldozer",
        "Bulldo": "Bulldozer"
    }
}